export default [
	`Wszędzie w domu, ale dobrze najlepiej.`,
	`Mam białego skina bo czarnego trzeba kupić.`,
	`Wszystko ma swoje zady i walety.`,
	`1C - jak cycki.`,
	`seks`,
	`bajabongo wariaciku`,
	`bagno`,
	`O której jutro kończymy? - Nie wiem. Trzeba w biblii sprawdzić`,
	`Dlaczego ty tu masz czipa? - Co? Cipa?`,
	`can we go break`,
	`animals are eat`,
	`Adam Tadeusz - Pan Mickiewicz`,
	`Czy wiedziałeś że 80 osób praworęcznych ma prawe ramię?`,
	`Wartacz to taki Wojciech Drewniak ale Bieda Edition`,
	`zed leppelin`,
	`I have an ask`,
	`Jeszcze nauczymy się sprzedawać bazy danych. Będziemy wszyscy bogaci.`,
	`A czy Pani mi uwierzy, jak powiem, że nie mogę teraz być na lekcji?`,
	`Dlaczego to jest tak, że rano do mnie znajomi piszą że umierają przez kaca, a ja nic nie czuję?`,
	`Ten dzień nie będzie dobry, będzie FANTASTYCZNY`,
	`Mamo, idziemy do pizdo...picolo`,
	`Stacja 7 - Adam umiera`,
	`Szyper: *sprawdził obecność*; Franek: Ale przecież pan nie zaznaczył; Szyper: Kuuuuurrrwaaaa`,
	`Szulada: Pewnego dnia wstawiłem uczniowi jedynkę. Wracając powiedział że już nic gorszego go tego dnia nie może spotkać. Może - mogę mu zwiększyć wagę...`,
	`fuck sie adrian`,
	`Co tutaj robi ten starszy pan z kotem? - Po pierwsze nie jestem stary, po drugie mam psa i po trzecie prowadzę lekcje`,
];
